### ISSUE TITLE
Use Case Formalization

### ISSUE THREAD

**Issue by BobdaFett** [WCSU-CS350-F24-Group-1/project-info#20]
### Use Case Formalization
- Formalize and document the use case.
- Upload and share the completed use case on Git by the end of the week.
- Sequence Diagram --> @VadimCh001

### Status Update
- Provide a current status update on Monday and maintain updates on Git.

**Comment by majerjake** [comment]
Hey Lucas. Will look to get those to you, I just recall you insisting to create a use case to better demonstrate the control/boundary objects last Thursday. Waiting on the reference, if not I can forward what I have by Wednesday.
