### ISSUE TITLE
Diagram Development and Refinement

### ISSUE THREAD

**Issue by NikitaKarim** [WCSU-CS350-F24-Group-1/project-info#21]
### Diagram Development
- Complete and refine the following diagrams:
- Use Case Diagram
- Object Diagram
- Control Diagram
- Sequence Diagram
- State Diagram
          
### Focus Areas:
- Derive classes into objects and integrate them into the use case structure.
- Fixes & Cleanup
      
### Address any required fixes or improvements based on feedback.
- Optimize and organize the frontend diagram for clarity.
- Documentation

### Update the Word document to incorporate new features.

**Comment by vcherem** [comment]
@BobdaFett need clarification on further enhancements for Sequence and Object diagrams, and **Derive classes into objects and integrate them into the use case structure.** - that's what Nikita said in issue #21
