### ISSUE TITLE
Branch Management, Merging, and Database Testing

### ISSUE THREAD

**Issue by NikitaKarim** [WCSU-CS350-F24-Group-1/project-info#25]
### Branch Management & Merging
- Merge the restructure into the master branch.
- Integrate the object and use case diagrams into the main documentation.

### Testing
- Test both object and use case diagrams for consistency and functionality.
- Review and test Marcos’s PostgreSQL database integration.

**Comment by Danises** [comment]
**Branch Management & Merging**

- Master branch restructure merged.
- Object and Use Case Diagrams merged into project-info.

**Testing**

- Test Case verified for Object and Use case Diagrams
- Marcos' PostgreSQL Database connection functionality was verified and the Test case was done.
