### ISSUE TITLE
Create Use Case & Sequence Diagram for: Update Student

### ISSUE THREAD

**Issue by NikitaKarim** [WCSU-CS350-F24-Group-1/project-info#30]
### Use Case: Update Student

Create comprehensive use case and sequence diagrams illustrating the process for updating student information. Include user interactions and relevant system responses. [Image](https://github.com/user-attachments/assets/6bd89f9a-4954-48f5-98fd-29b8beb21e0f)

usecases.png : https://github.com/WCSU-CS350-F24-Group-1/project-info/blob/feat/add-usecases/Diagrams/Usecases/usecases.png

**Comment by Jasnski** [comment]
![Image](https://github.com/user-attachments/assets/a34c4d6c-08f3-45bf-ad2d-0272ed271d7a)
![Image](https://github.com/user-attachments/assets/93f46524-2625-47a9-8e54-0a6b5af791be)
