### ISSUE TITLE
Create Use Case & Sequence Diagram for: Update Course

### ISSUE THREAD

**Issue by NikitaKarim** [WCSU-CS350-F24-Group-1/project-info#32]
### Use Case: Update Course

Construct thorough use case and sequence diagrams that depict the process for updating course details. Include user inputs, system validations, and updates to the course records.![Image](https://github.com/user-attachments/assets/43e673f2-da82-4db0-9eec-2651799d6a9a)

usecases.png : https://github.com/WCSU-CS350-F24-Group-1/project-info/blob/feat/add-usecases/Diagrams/Usecases/usecases.png

**Comment by polonextdoor** [comment]
diagrams and use case made, made pull request on separate branch 👍
